<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorRoleTableSeeder extends Seeder
{
    public function run()
    {
        $translations = TranslatedAttributesSeeder::getActorRoles();
        DB::table('actor_role')->insertOrIgnore([
            [
                'code' => 'ADV',
                'name' => json_encode($translations['ADV']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AGT',
                'name' => json_encode($translations['AGT']),
                'display_order' => 20,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AGT2',
                'name' => json_encode($translations['AGT2']),
                'display_order' => 22,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Usually primary agent\'s agent',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANN',
                'name' => json_encode($translations['ANN']),
                'display_order' => 21,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'APP',
                'name' => json_encode($translations['APP']),
                'display_order' => 10,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CLI',
                'name' => json_encode($translations['CLI']),
                'display_order' => 5,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CNT',
                'name' => json_encode($translations['CNT']),
                'display_order' => 30,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DBA',
                'name' => json_encode($translations['DBA']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DBRO',
                'name' => json_encode($translations['DBRO']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DBRW',
                'name' => json_encode($translations['DBRW']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DEL',
                'name' => json_encode($translations['DEL']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FAGT',
                'name' => json_encode($translations['FAGT']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FOWN',
                'name' => json_encode($translations['FOWN']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'INV',
                'name' => json_encode($translations['INV']),
                'display_order' => 15,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LCN',
                'name' => json_encode($translations['LCN']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OFF',
                'name' => json_encode($translations['OFF']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OPP',
                'name' => json_encode($translations['OPP']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OWN',
                'name' => json_encode($translations['OWN']),
                'display_order' => 8,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PAY',
                'name' => json_encode($translations['PAY']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTNR',
                'name' => json_encode($translations['PTNR']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TRA',
                'name' => json_encode($translations['TRA']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'WRI',
                'name' => json_encode($translations['WRI']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
