<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventNameTableSeeder extends Seeder
{
    public function run()
    {
        $translations = TranslatedAttributesSeeder::getEventNames();

        DB::table('event_name')->insertOrIgnore([

            [
                'code' => 'ABA',
                'name' => json_encode($translations['ABA']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ABO',
                'name' => json_encode($translations['ABO']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Abandon the originating patent that was re-designated in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ADV',
                'name' => json_encode($translations['ADV']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ALL',
                'name' => json_encode($translations['ALL']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use also for R71.3 in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'APL',
                'name' => json_encode($translations['APL']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Appeal or other remedy filed',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CAN',
                'name' => json_encode($translations['CAN']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CLO',
                'name' => json_encode($translations['CLO']),
                'category' => 'LTG',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'COM',
                'name' => json_encode($translations['COM']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Communication regarding administrative or formal matters (missing parts, irregularities...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CRE',
                'name' => json_encode($translations['CRE']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Creation date of matter - for attaching tasks necessary before anything else',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DAPL',
                'name' => json_encode($translations['DAPL']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'State outcome in detail field',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBY',
                'name' => json_encode($translations['DBY']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DEX',
                'name' => json_encode($translations['DEX']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Deadline extension requested',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DPAPL',
                'name' => json_encode($translations['DPAPL']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DRA',
                'name' => json_encode($translations['DRA']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DW',
                'name' => json_encode($translations['DW']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Decision needing a reply, such as further processing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EHK',
                'name' => json_encode($translations['EHK']),
                'category' => 'PAT',
                'country' => 'CN',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ENT',
                'name' => json_encode($translations['ENT']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'National entry date from PCT phase',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EOP',
                'name' => json_encode($translations['EOP']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Indicates the end of a regional procedure, such as when the EP patent is granted',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXA',
                'name' => json_encode($translations['EXA']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'AKA Office Action, i.e. anything related to substantive examination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXAF',
                'name' => json_encode($translations['EXAF']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXP',
                'name' => json_encode($translations['EXP']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Do not use nor change - present for internal functionality',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FAP',
                'name' => json_encode($translations['FAP']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FBY',
                'name' => json_encode($translations['FBY']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FDIV',
                'name' => json_encode($translations['FDIV']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FIL',
                'name' => json_encode($translations['FIL']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FOP',
                'name' => json_encode($translations['FOP']),
                'category' => 'OP',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FPR',
                'name' => json_encode($translations['FPR']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FRCE',
                'name' => json_encode($translations['FRCE']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'GRT',
                'name' => json_encode($translations['GRT']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'INV',
                'name' => json_encode($translations['INV']),
                'category' => 'TM',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'IPER',
                'name' => json_encode($translations['IPER']),
                'category' => 'PAT',
                'country' => 'WO',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Chapter II of PCT examination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LAP',
                'name' => json_encode($translations['LAP']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'NPH',
                'name' => json_encode($translations['NPH']),
                'category' => 'PAT',
                'country' => 'WO',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPP',
                'name' => json_encode($translations['OPP']),
                'category' => null,
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORI',
                'name' => json_encode($translations['ORI']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Original matter from which others derive',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPR',
                'name' => json_encode($translations['OPR']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORE',
                'name' => json_encode($translations['ORE']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PAY',
                'name' => json_encode($translations['PAY']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use for any fees to be paid',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PDES',
                'name' => json_encode($translations['PDES']),
                'category' => 'TM',
                'country' => 'WO',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PFIL',
                'name' => json_encode($translations['PFIL']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Filing date of the parent (use only when the matter type is defined). Use as link to the parent matter.',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PR',
                'name' => json_encode($translations['PR']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PREP',
                'name' => json_encode($translations['PREP']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further action to be done by the responsible (comments, pre-handling, ...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRI',
                'name' => json_encode($translations['PRI']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use as link to the priority matter',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRID',
                'name' => json_encode($translations['PRID']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PROD',
                'name' => json_encode($translations['PROD']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further documents to be filed (inventor designation, priority document, missing parts...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PSR',
                'name' => json_encode($translations['PSR']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'A3 publication',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PUB',
                'name' => json_encode($translations['PUB']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'For EP, this means publication WITH the search report (A1 publ.)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RCE',
                'name' => json_encode($translations['RCE']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REC',
                'name' => json_encode($translations['REC']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Date the case was received from the client',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REF',
                'name' => json_encode($translations['REF']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'This is the final decision, that can only be appealed - do not mistake with an exam report',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REJF',
                'name' => json_encode($translations['REJF']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => 'Final rejection that can only be overcome by RCE or appeal',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REG',
                'name' => json_encode($translations['REG']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REM',
                'name' => json_encode($translations['REM']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REN',
                'name' => json_encode($translations['REN']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REP',
                'name' => json_encode($translations['REP']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REST',
                'name' => json_encode($translations['REST']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Case restored after abandonment, lapse, or other termination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REQ',
                'name' => json_encode($translations['REQ']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RSTR',
                'name' => json_encode($translations['RSTR']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOL',
                'name' => json_encode($translations['SOL']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOP',
                'name' => json_encode($translations['SOP']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SR',
                'name' => json_encode($translations['SR']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SUS',
                'name' => json_encode($translations['SUS']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SUO',
                'name' => json_encode($translations['SUO']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Summons to oral proceedings or hearing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRF',
                'name' => json_encode($translations['TRF']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRS',
                'name' => json_encode($translations['TRS']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'VAL',
                'name' => json_encode($translations['VAL']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WAT',
                'name' => json_encode($translations['WAT']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WIT',
                'name' => json_encode($translations['WIT']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WO',
                'name' => json_encode($translations['WO']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'International PCT application filing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
