<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventNameTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('event_name')->insertOrIgnore([

            [
                'code' => 'ABA',
                'name' => json_encode(['en' => 'Abandoned', 'fr' => 'Abandonné', 'de' => 'Aufgegeben', 'zh' => '放弃']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ABO',
                'name' => json_encode(['en' => 'Abandon Original', 'fr' => 'Abandon original', 'de' => 'Ursprüngliches aufgeben', 'zh' => '放弃原案']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Abandon the originating patent that was re-designated in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ADV',
                'name' => json_encode(['en' => 'Advisory Action', 'fr' => 'Advisory Action', 'de' => 'Advisory Action', 'zh' => '咨询意见']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ALL',
                'name' => json_encode(['en' => 'Allowance', 'fr' => 'Intention délivrance', 'de' => 'Zulassung', 'zh' => '授权意向']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use also for R71.3 in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'APL',
                'name' => json_encode(['en' => 'Appeal', 'fr' => 'Recours', 'de' => 'Beschwerde', 'zh' => '上诉']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Appeal or other remedy filed',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CAN',
                'name' => json_encode(['en' => 'Cancelled', 'fr' => 'Annulé', 'de' => 'Storniert', 'zh' => '取消']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CLO',
                'name' => json_encode(['en' => 'Closed', 'fr' => 'Clôturé', 'de' => 'Geschlossen', 'zh' => '关闭']),
                'category' => 'LTG',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'COM',
                'name' => json_encode(['en' => 'Communication', 'fr' => 'Communication', 'de' => 'Mitteilung', 'zh' => '通知']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Communication regarding administrative or formal matters (missing parts, irregularities...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CRE',
                'name' => json_encode(['en' => 'Created', 'fr' => 'Création', 'de' => 'Erstellt', 'zh' => '创建']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Creation date of matter - for attaching tasks necessary before anything else',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DAPL',
                'name' => json_encode(['en' => 'Decision on Appeal', 'fr' => 'Décision sur recours', 'de' => 'Beschwerdeentscheidung', 'zh' => '上诉决定']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'State outcome in detail field',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBY',
                'name' => json_encode(['en' => 'Draft By', 'fr' => 'Rédiger avant le', 'de' => 'Entwurf bis', 'zh' => '起草截止']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DEX',
                'name' => json_encode(['en' => 'Deadline Extended', 'fr' => 'Délai prolongé', 'de' => 'Frist verlängert', 'zh' => '期限延长']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Deadline extension requested',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DPAPL',
                'name' => json_encode(['en' => 'Decision on Pre-Appeal', 'fr' => 'Décision pré-recours', 'de' => 'Vorentscheidung', 'zh' => '预上诉决定']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DRA',
                'name' => json_encode(['en' => 'Drafted', 'fr' => 'Rédigé', 'de' => 'Entworfen', 'zh' => '已起草']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DW',
                'name' => json_encode(['en' => 'Deemed withrawn', 'fr' => 'Réputé retiré', 'de' => 'Als zurückgenommen geltend', 'zh' => '视为撤回']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Decision needing a reply, such as further processing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EHK',
                'name' => json_encode(['en' => 'Extend to Hong Kong', 'fr' => 'Étendre à Hong Kong', 'de' => 'Erstreckung auf Hongkong', 'zh' => '延伸至香港']),
                'category' => 'PAT',
                'country' => 'CN',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ENT',
                'name' => json_encode(['en' => 'Entered', 'fr' => 'Entrée', 'de' => 'Eingetreten', 'zh' => '进入']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'National entry date from PCT phase',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EOP',
                'name' => json_encode(['en' => 'End of Procedure', 'fr' => 'Fin de procédure', 'de' => 'Verfahrensende', 'zh' => '程序结束']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Indicates the end of a regional procedure, such as when the EP patent is granted',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXA',
                'name' => json_encode(['en' => 'Examiner Action', 'fr' => 'Notification d\'examen', 'de' => 'Prüferbescheid', 'zh' => '审查意见']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'AKA Office Action, i.e. anything related to substantive examination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXAF',
                'name' => json_encode(['en' => 'Examiner Action (Final)', 'fr' => 'Notif. Exa. (Finale)', 'de' => 'Schlussbescheid Prüfer', 'zh' => '审查意见（终局）']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXP',
                'name' => json_encode(['en' => 'Expiry', 'fr' => 'Expiration', 'de' => 'Ablauf', 'zh' => '届满']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Do not use nor change - present for internal functionality',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FAP',
                'name' => json_encode(['en' => 'File Notice of Appeal', 'fr' => 'Déposer avis de recours', 'de' => 'Beschwerde einlegen', 'zh' => '提交上诉通知']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FBY',
                'name' => json_encode(['en' => 'File by', 'fr' => 'Déposer avant le', 'de' => 'Einreichen bis', 'zh' => '提交截止']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FDIV',
                'name' => json_encode(['en' => 'File Divisional', 'fr' => 'Déposer divisionnaire', 'de' => 'Teilanmeldung einreichen', 'zh' => '提交分案']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FIL',
                'name' => json_encode(['en' => 'Filed', 'fr' => 'Déposé', 'de' => 'Eingereicht', 'zh' => '已提交']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FOP',
                'name' => json_encode(['en' => 'File Opposition', 'fr' => 'Déposer opposition', 'de' => 'Einspruch einlegen', 'zh' => '提交异议']),
                'category' => 'OP',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FPR',
                'name' => json_encode(['en' => 'Further Processing', 'fr' => 'Poursuite procédure', 'de' => 'Weiterbehandlung', 'zh' => '继续处理']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FRCE',
                'name' => json_encode(['en' => 'File RCE', 'fr' => 'Déposer RCE', 'de' => 'RCE einreichen', 'zh' => '提交RCE']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'GRT',
                'name' => json_encode(['en' => 'Granted', 'fr' => 'Délivré', 'de' => 'Erteilt', 'zh' => '已授权']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'INV',
                'name' => json_encode(['en' => 'Invalidated', 'fr' => 'Invalidé', 'de' => 'Für ungültig erklärt', 'zh' => '无效']),
                'category' => 'TM',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'IPER',
                'name' => json_encode(['en' => 'International Preliminary Examination Report', 'fr' => 'Rapport d\'examen préliminaire international', 'de' => 'Internationaler vorläufiger Prüfungsbericht', 'zh' => '国际初步审查报告']),
                'category' => 'PAT',
                'country' => 'WO',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Chapter II of PCT examination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LAP',
                'name' => json_encode(['en' => 'Lapsed', 'fr' => 'Déchu', 'de' => 'Verfallen', 'zh' => '失效']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'NPH',
                'name' => json_encode(['en' => 'National Phase', 'fr' => 'Phase nationale', 'de' => 'Nationale Phase', 'zh' => '国家阶段']),
                'category' => 'PAT',
                'country' => 'WO',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPP',
                'name' => json_encode(['en' => 'Opposition', 'fr' => 'Opposition', 'de' => 'Einspruch', 'zh' => '异议']),
                'category' => null,
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORI',
                'name' => json_encode(['en' => 'Original', 'fr' => 'Original', 'de' => 'Original', 'zh' => '原始']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Original matter from which others derive',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPR',
                'name' => json_encode(['en' => 'Oral Proceedings', 'fr' => 'Procédure orale', 'de' => 'Mündliche Verhandlung', 'zh' => '口头审理']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORE',
                'name' => json_encode(['en' => 'Opposition rejected', 'fr' => 'Opposition rejetée', 'de' => 'Einspruch zurückgewiesen', 'zh' => '异议被驳回']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PAY',
                'name' => json_encode(['en' => 'Pay', 'fr' => 'Payer', 'de' => 'Zahlen', 'zh' => '支付']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use for any fees to be paid',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PDES',
                'name' => json_encode(['en' => 'Post designation', 'fr' => 'Désignation postérieure', 'de' => 'Nachträgliche Benennung', 'zh' => '后续指定']),
                'category' => 'TM',
                'country' => 'WO',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PFIL',
                'name' => json_encode(['en' => 'Parent Filed', 'fr' => 'Dépôt parent', 'de' => 'Stammanmeldung eingereicht', 'zh' => '母案提交']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Filing date of the parent (use only when the matter type is defined). Use as link to the parent matter.',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PR',
                'name' => json_encode(['en' => 'Publication of Reg.', 'fr' => 'Publication enreg.', 'de' => 'Veröffentlichung Reg.', 'zh' => '注册公告']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PREP',
                'name' => json_encode(['en' => 'Prepare', 'fr' => 'Préparer', 'de' => 'Vorbereiten', 'zh' => '准备']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further action to be done by the responsible (comments, pre-handling, ...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRI',
                'name' => json_encode(['en' => 'Priority Claim', 'fr' => 'Revendication priorité', 'de' => 'Prioritätsanspruch', 'zh' => '优先权']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use as link to the priority matter',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRID',
                'name' => json_encode(['en' => 'Priority Deadline', 'fr' => 'Délai priorité', 'de' => 'Prioritätsfrist', 'zh' => '优先权期限']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PROD',
                'name' => json_encode(['en' => 'Produce', 'fr' => 'Produire', 'de' => 'Erstellen/Einreichen', 'zh' => '提供']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further documents to be filed (inventor designation, priority document, missing parts...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PSR',
                'name' => json_encode(['en' => 'Publication of SR', 'fr' => 'Publication rap. rech.', 'de' => 'Veröffentlichung Rech.ber.', 'zh' => '检索报告公布']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'A3 publication',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PUB',
                'name' => json_encode(['en' => 'Published', 'fr' => 'Publié', 'de' => 'Veröffentlicht', 'zh' => '已公布']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'For EP, this means publication WITH the search report (A1 publ.)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RCE',
                'name' => json_encode(['en' => 'Request Continued Examination', 'fr' => 'Requête RCE', 'de' => 'Antrag auf Fortsetzung Prüfung', 'zh' => '请求继续审查']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REC',
                'name' => json_encode(['en' => 'Received', 'fr' => 'Reçu', 'de' => 'Empfangen', 'zh' => '已收到']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Date the case was received from the client',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REF',
                'name' => json_encode(['en' => 'Refused', 'fr' => 'Refusé', 'de' => 'Zurückgewiesen', 'zh' => '驳回']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'This is the final decision, that can only be appealed - do not mistake with an exam report',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REJF',
                'name' => json_encode(['en' => 'Rejection Final', 'fr' => 'Rejet définitif', 'de' => 'Endgültige Ablehnung', 'zh' => '最终驳回']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => 'Final rejection that can only be overcome by RCE or appeal',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REG',
                'name' => json_encode(['en' => 'Registration', 'fr' => 'Enregistrement', 'de' => 'Registrierung', 'zh' => '注册']),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REM',
                'name' => json_encode(['en' => 'Reminder', 'fr' => 'Rappel', 'de' => 'Erinnerung', 'zh' => '提醒']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REN',
                'name' => json_encode(['en' => 'Renewal', 'fr' => 'Renouvellement', 'de' => 'Verlängerung', 'zh' => '续展']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REP',
                'name' => json_encode(['en' => 'Respond', 'fr' => 'Répondre', 'de' => 'Erwidern', 'zh' => '答复']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REST',
                'name' => json_encode(['en' => 'Restored', 'fr' => 'Restauré', 'de' => 'Wiederhergestellt', 'zh' => '恢复']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Case restored after abandonment, lapse, or other termination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REQ',
                'name' => json_encode(['en' => 'Request', 'fr' => 'Requête', 'de' => 'Antrag', 'zh' => '请求']),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RSTR',
                'name' => json_encode(['en' => 'Restriction Req.', 'fr' => 'Requête restriction', 'de' => 'Beschränkungsantrag', 'zh' => '限制请求']),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOL',
                'name' => json_encode(['en' => 'Sold', 'fr' => 'Vendu', 'de' => 'Verkauft', 'zh' => '已转让']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOP',
                'name' => json_encode(['en' => 'Summons to Oral Proc.', 'fr' => 'Citation proc. orale', 'de' => 'Ladung zur Mündl. Verh.', 'zh' => '传唤口头审理']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SR',
                'name' => json_encode(['en' => 'Search Report', 'fr' => 'Rapport de recherche', 'de' => 'Recherchenbericht', 'zh' => '检索报告']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SUS',
                'name' => json_encode(['en' => 'Suspended', 'fr' => 'Suspendu', 'de' => 'Ausgesetzt', 'zh' => '中止']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SUO',
                'name' => json_encode(['en' => 'Summons Oral', 'fr' => 'Convocation procédure orale', 'de' => 'Ladung mündliche Verhandlung', 'zh' => '传唤口头审理']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Summons to oral proceedings or hearing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRF',
                'name' => json_encode(['en' => 'Transformation', 'fr' => 'Transformation', 'de' => 'Transformation', 'zh' => '转化']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRS',
                'name' => json_encode(['en' => 'Transfer', 'fr' => 'Transfert', 'de' => 'Übertragung', 'zh' => '转让']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'VAL',
                'name' => json_encode(['en' => 'Validate', 'fr' => 'Valider', 'de' => 'Validieren', 'zh' => '验证']),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WAT',
                'name' => json_encode(['en' => 'Watch', 'fr' => 'Surveiller', 'de' => 'Überwachen', 'zh' => '监视']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WIT',
                'name' => json_encode(['en' => 'Withdrawal', 'fr' => 'Retrait', 'de' => 'Zurücknahme', 'zh' => '撤回']),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WO',
                'name' => json_encode(['en' => 'PCT', 'fr' => 'PCT', 'de' => 'PCT', 'zh' => 'PCT']),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'International PCT application filing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
