<?php

namespace App\Models;

use App\Enums\CategoryCode;
use App\Enums\EventCode;
use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Event Model
 *
 * Represents important dates and milestones in a matter's lifecycle, such as:
 * - Filing dates (FIL)
 * - Publication dates (PUB)
 * - Grant/registration dates (GRT/REG)
 * - Priority dates (PRI)
 * - Deadlines and status changes
 *
 * Database table: event
 *
 * Key relationships:
 * - Belongs to a matter
 * - Can link to an alternate matter (for priority claims, etc.)
 * - Has many tasks (automatic reminders/deadlines)
 * - Has event name info (description and classification)
 *
 * Business logic:
 * - Events automatically touch (update timestamp of) their parent matter
 * - Events can generate tasks based on rules
 * - Events can link matters together (priority, parent-child relationships)
 * - Provides methods to generate URLs to official patent/trademark registers
 */
class Event extends Model
{
    use Auditable;
    use HasFactory;

    /**
     * Attributes to exclude from audit logging.
     *
     * @var array<string>
     */
    protected $auditExclude = ['created_at', 'updated_at'];

    /**
     * The database table associated with the model.
     *
     * @var string
     */
    protected $table = 'event';

    /**
     * Attributes that should be hidden from serialization.
     *
     * @var array<string>
     */
    protected $hidden = ['creator', 'created_at', 'updated_at', 'updater'];

    /**
     * Attributes that are not mass assignable.
     *
     * @var array<string>
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     * Related models that should be touched when this model is updated.
     *
     * Updates the matter's timestamp when an event changes.
     *
     * @var array<string>
     */
    protected $touches = ['matter'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'event_date' => 'date:Y-m-d',
    ];

    /**
     * Get the event name information.
     *
     * Returns the EventName model containing description, classification,
     * and other metadata about this event type.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function info()
    {
        return $this->belongsTo(EventName::class, 'code', 'code');
    }

    /**
     * Get the matter this event belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function matter()
    {
        return $this->belongsTo(Matter::class);
    }

    /**
     * Get the alternate matter linked to this event.
     *
     * Used for priority claims, parent-child relationships, etc.
     * Returns a default empty model if no alternate matter is linked.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function altMatter()
    {
        return $this->belongsTo(Matter::class, 'alt_matter_id')->withDefault();
    }

    /**
     * Get the filing event of the alternate matter.
     *
     * Used to retrieve filing details of priority applications.
     * Returns a default empty model if no link exists.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function link()
    {
        return $this->hasOne(Event::class, 'matter_id', 'alt_matter_id')->whereCode(EventCode::FILING->value)->withDefault();
    }

    /**
     * Get the reverse link to this event.
     *
     * Used for bidirectional event linking.
     * Returns a default empty model if no retro link exists.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function retroLink()
    {
        return $this->belongsTo(Event::class, 'matter_id', 'alt_matter_id')->withDefault();
    }

    /**
     * Get all tasks generated by this event.
     *
     * Tasks are automatic reminders and deadlines created from rules.
     * Results are ordered by due date.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tasks()
    {
        return $this->hasMany(Task::class, 'trigger_id')->orderBy('due_date');
    }

    /**
     * Clean and normalize the event detail number.
     *
     * Removes country code prefix, spaces, commas, hyphens, slashes,
     * and decimal portions to create a standardized number format
     * suitable for URL construction and comparison.
     *
     * @return string The cleaned number
     */
    public function cleanNumber()
    {
        return preg_replace(["/^{$this->matter->country}/", '/ /', '/,/', '/-/', '/\//', '/\.[0-9]/'], '', $this->detail);
    }

    /**
     * Generate a URL to the official patent/trademark register for this event.
     *
     * Creates links to:
     * - Espacenet (worldwide patent database)
     * - EPO Register (European patents)
     * - INPI (French patents and trademarks)
     * - USPTO (US patents)
     * - IPO (UK patents)
     * - EUIPO (EU trademarks)
     *
     * Only works for filing (FIL), publication (PUB), and grant (GRT) events.
     *
     * @return string|false The URL to the official register, or false if not applicable
     */
    public function publicUrl()
    {
        $validCodes = [EventCode::FILING->value, EventCode::PUBLICATION->value, EventCode::GRANT->value];
        if (! in_array($this->code, $validCodes)) {
            return false;
        }
        if ($this->matter->origin == 'EP') {
            $CC = 'EP';
        } else {
            $CC = $this->matter->country;
        }
        $category = $this->matter->category_code;
        $cleanednumber = $this->cleanNumber();
        $href = '';
        $pubno = '';
        if ($this->code == EventCode::PUBLICATION->value || $this->code == EventCode::GRANT->value) {
            // Fix US pub number for Espacenet by keeping the last 6 digits after the year
            if ($CC == 'US' && $this->code == EventCode::PUBLICATION->value) {
                $cleanednumber = substr($cleanednumber, 0, 4).substr($cleanednumber, -6);
            }
            $href = config('patent_offices.espacenet.publication')."?DB=EPODOC&CC=$CC&NR=$cleanednumber";
        } elseif ($this->code == EventCode::FILING->value) {
            $country = $this->matter->country;
            $registryConfig = config("patent_offices.registries.$country");

            if ($registryConfig) {
                $href = $this->buildRegistryUrl($registryConfig, $cleanednumber, $CC, $category);
            }
        }

        return $href;
    }

    /**
     * Build a registry URL based on the configuration.
     *
     * @param  array  $config  The registry configuration
     * @param  string  $cleanednumber  The cleaned number
     * @param  string  $CC  The country code
     * @param  string  $category  The matter category code
     * @return string The built URL
     */
    protected function buildRegistryUrl(array $config, string $cleanednumber, string $CC, string $category): string
    {
        $href = '';

        switch ($this->matter->country) {
            case 'EP':
                $href = str_replace('{number}', $cleanednumber, $config['filing']);
                break;
            case 'FR':
                $pubno = $this->matter->publication->cleanNumber();
                if ($category == CategoryCode::PATENT->value && $pubno) {
                    $href = str_replace(['{cc}', '{number}'], [$CC, $pubno], $config['patent']);
                } elseif ($category == CategoryCode::TRADEMARK->value) {
                    if ($this->event_date->isoFormat('YYYY') >= '2000') {
                        $cleanednumber = substr($cleanednumber, -7);
                    }
                    $href = str_replace(['{cc}', '{number}'], [$CC, $cleanednumber], $config['trademark']);
                }
                break;
            case 'US':
                if (substr($cleanednumber, 0, 2) < 13) {
                    $cleanednumber = substr($cleanednumber, 2).$this->event_date->isoFormat('YY');
                } else {
                    $cleanednumber = $this->event_date->isoFormat('YYYY').$cleanednumber;
                }
                $href = str_replace('{number}', $cleanednumber, $config['filing']);
                break;
            case 'GB':
                $href = str_replace(['{cc}', '{number}'], [$CC, $cleanednumber], $config['filing']);
                break;
            case 'EM':
                $href = str_replace('{number}', $cleanednumber, $config['trademark']);
                break;
        }

        return $href;
    }
}
